import type { Recipe } from '../types'

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'seed-1',
    name: 'Overnight Oats',
    description: 'Prep-ahead creamy oats with banana and honey — zero morning effort.',
    category: 'breakfast',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 2,
    cost_per_serving: 0.75,
    total_cost: 1.50,
    tags: ['vegetarian', 'meal-prep', 'no-cook'],
    instructions: 'Combine oats, milk, and chia seeds in a jar. Stir well. Refrigerate overnight. In the morning, top with sliced banana and drizzle with honey.',
    ingredients: [
      { name: 'Rolled Oats', quantity: '1 cup', estimated_cost: 0.40, category: 'Pantry' },
      { name: 'Milk', quantity: '1 cup', estimated_cost: 0.30, category: 'Dairy & Eggs' },
      { name: 'Chia Seeds', quantity: '1 tbsp', estimated_cost: 0.20, category: 'Pantry' },
      { name: 'Banana', quantity: '1 medium', estimated_cost: 0.30, category: 'Produce' },
      { name: 'Honey', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-2',
    name: 'Scrambled Eggs & Toast',
    description: 'Classic fluffy scrambled eggs with buttered toast. Quick and satisfying.',
    category: 'breakfast',
    prep_time_minutes: 3,
    cook_time_minutes: 7,
    servings: 2,
    cost_per_serving: 1.20,
    total_cost: 2.40,
    tags: ['vegetarian', 'quick', 'protein'],
    instructions: 'Whisk eggs with a pinch of salt and pepper. Melt butter in a pan over medium-low heat. Add eggs and gently fold with a spatula until just set. Serve on toast.',
    ingredients: [
      { name: 'Eggs', quantity: '4 large', estimated_cost: 1.20, category: 'Dairy & Eggs' },
      { name: 'Bread', quantity: '4 slices', estimated_cost: 0.60, category: 'Bread & Bakery' },
      { name: 'Butter', quantity: '1 tbsp', estimated_cost: 0.15, category: 'Dairy & Eggs' },
      { name: 'Salt', quantity: 'pinch', estimated_cost: 0.01, category: 'Pantry' },
      { name: 'Black Pepper', quantity: 'pinch', estimated_cost: 0.02, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-3',
    name: 'Banana Pancakes',
    description: 'Fluffy golden pancakes with ripe banana folded right in.',
    category: 'breakfast',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    cost_per_serving: 0.90,
    total_cost: 3.60,
    tags: ['vegetarian', 'family-friendly'],
    instructions: 'Mash bananas and mix with egg and milk. Fold in flour, baking powder, and a pinch of salt. Cook in a buttered pan over medium heat until bubbles form, then flip.',
    ingredients: [
      { name: 'All-Purpose Flour', quantity: '1 cup', estimated_cost: 0.20, category: 'Pantry' },
      { name: 'Eggs', quantity: '2 large', estimated_cost: 0.60, category: 'Dairy & Eggs' },
      { name: 'Milk', quantity: '¾ cup', estimated_cost: 0.25, category: 'Dairy & Eggs' },
      { name: 'Bananas', quantity: '2 ripe', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Baking Powder', quantity: '1 tsp', estimated_cost: 0.05, category: 'Pantry' },
      { name: 'Butter', quantity: '2 tbsp', estimated_cost: 0.20, category: 'Dairy & Eggs' },
      { name: 'Maple Syrup', quantity: '¼ cup', estimated_cost: 1.90, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-4',
    name: 'Greek Yogurt Parfait',
    description: 'Layers of creamy yogurt, crunchy granola, and fresh berries.',
    category: 'breakfast',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    cost_per_serving: 1.50,
    total_cost: 1.50,
    tags: ['vegetarian', 'no-cook', 'protein', 'quick'],
    instructions: 'Layer Greek yogurt, granola, and mixed berries in a bowl or glass. Drizzle with honey.',
    ingredients: [
      { name: 'Greek Yogurt', quantity: '¾ cup', estimated_cost: 0.70, category: 'Dairy & Eggs' },
      { name: 'Granola', quantity: '¼ cup', estimated_cost: 0.40, category: 'Pantry' },
      { name: 'Mixed Berries', quantity: '½ cup', estimated_cost: 1.00, category: 'Produce' },
      { name: 'Honey', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-5',
    name: 'Red Lentil Soup',
    description: 'Hearty, warming red lentil soup with cumin and lemon. Freezes beautifully.',
    category: 'lunch',
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 6,
    cost_per_serving: 1.20,
    total_cost: 7.20,
    tags: ['vegan', 'meal-prep', 'high-protein', 'freezer-friendly'],
    instructions: 'Sauté onion and garlic in olive oil. Add cumin, then lentils, carrots, and broth. Simmer 25 minutes until lentils dissolve. Finish with lemon juice and salt.',
    ingredients: [
      { name: 'Red Lentils', quantity: '1.5 cups', estimated_cost: 1.20, category: 'Pantry' },
      { name: 'Onion', quantity: '1 large', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Garlic', quantity: '3 cloves', estimated_cost: 0.20, category: 'Produce' },
      { name: 'Carrots', quantity: '2 medium', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Vegetable Broth', quantity: '6 cups', estimated_cost: 1.50, category: 'Pantry' },
      { name: 'Ground Cumin', quantity: '1 tsp', estimated_cost: 0.15, category: 'Pantry' },
      { name: 'Olive Oil', quantity: '2 tbsp', estimated_cost: 0.30, category: 'Pantry' },
      { name: 'Lemon', quantity: '1', estimated_cost: 0.50, category: 'Produce' },
    ],
  },
  {
    id: 'seed-6',
    name: 'Black Bean Tacos',
    description: 'Speedy weeknight tacos with seasoned black beans and fresh toppings.',
    category: 'lunch',
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings: 4,
    cost_per_serving: 1.40,
    total_cost: 5.60,
    tags: ['vegetarian', 'quick', 'family-friendly'],
    instructions: 'Season drained black beans with cumin and garlic powder, warm in a pan. Warm tortillas. Assemble with beans, salsa, shredded cheese, and a squeeze of lime.',
    ingredients: [
      { name: 'Black Beans (canned)', quantity: '2 cans (15oz)', estimated_cost: 1.60, category: 'Pantry' },
      { name: 'Small Flour Tortillas', quantity: '8', estimated_cost: 1.50, category: 'Bread & Bakery' },
      { name: 'Shredded Cheese', quantity: '1 cup', estimated_cost: 1.50, category: 'Dairy & Eggs' },
      { name: 'Salsa', quantity: '½ cup', estimated_cost: 0.80, category: 'Pantry' },
      { name: 'Lime', quantity: '1', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Ground Cumin', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
      { name: 'Garlic Powder', quantity: '½ tsp', estimated_cost: 0.05, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-7',
    name: 'Veggie Fried Rice',
    description: 'Better-than-takeout fried rice using leftover rice and pantry staples.',
    category: 'lunch',
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    cost_per_serving: 1.30,
    total_cost: 5.20,
    tags: ['vegetarian', 'quick', 'meal-prep', 'leftover-friendly'],
    instructions: 'Heat oil in a wok or large skillet. Add garlic and ginger, then vegetables. Push to the side, scramble eggs. Add cold rice and soy sauce, stir-fry until heated through.',
    ingredients: [
      { name: 'Cooked Rice', quantity: '3 cups cold', estimated_cost: 0.60, category: 'Pantry' },
      { name: 'Eggs', quantity: '3 large', estimated_cost: 0.90, category: 'Dairy & Eggs' },
      { name: 'Frozen Mixed Vegetables', quantity: '2 cups', estimated_cost: 1.50, category: 'Frozen' },
      { name: 'Soy Sauce', quantity: '3 tbsp', estimated_cost: 0.30, category: 'Pantry' },
      { name: 'Sesame Oil', quantity: '1 tsp', estimated_cost: 0.20, category: 'Pantry' },
      { name: 'Garlic', quantity: '2 cloves', estimated_cost: 0.15, category: 'Produce' },
      { name: 'Ginger', quantity: '1 tsp', estimated_cost: 0.15, category: 'Produce' },
      { name: 'Vegetable Oil', quantity: '2 tbsp', estimated_cost: 0.20, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-8',
    name: 'Tuna Salad Sandwich',
    description: 'Classic tuna salad with celery and pickle on hearty bread.',
    category: 'lunch',
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    servings: 2,
    cost_per_serving: 1.80,
    total_cost: 3.60,
    tags: ['no-cook', 'quick', 'high-protein'],
    instructions: 'Drain tuna and mix with mayo, chopped celery, and pickle relish. Season with salt and pepper. Serve on bread with lettuce.',
    ingredients: [
      { name: 'Canned Tuna', quantity: '2 cans (5oz)', estimated_cost: 2.40, category: 'Pantry' },
      { name: 'Mayonnaise', quantity: '3 tbsp', estimated_cost: 0.30, category: 'Pantry' },
      { name: 'Celery', quantity: '2 stalks', estimated_cost: 0.30, category: 'Produce' },
      { name: 'Pickle Relish', quantity: '1 tbsp', estimated_cost: 0.15, category: 'Pantry' },
      { name: 'Whole Wheat Bread', quantity: '4 slices', estimated_cost: 0.70, category: 'Bread & Bakery' },
      { name: 'Lettuce', quantity: '4 leaves', estimated_cost: 0.30, category: 'Produce' },
    ],
  },
  {
    id: 'seed-9',
    name: 'Peanut Butter Banana Wrap',
    description: 'Simple, filling wrap with peanut butter and banana. Great for on the go.',
    category: 'snack',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    cost_per_serving: 0.90,
    total_cost: 0.90,
    tags: ['vegan', 'no-cook', 'quick', 'kid-friendly'],
    instructions: 'Spread peanut butter on tortilla. Place banana at one edge and roll up tightly. Drizzle with honey if desired.',
    ingredients: [
      { name: 'Large Flour Tortilla', quantity: '1', estimated_cost: 0.30, category: 'Bread & Bakery' },
      { name: 'Peanut Butter', quantity: '2 tbsp', estimated_cost: 0.30, category: 'Pantry' },
      { name: 'Banana', quantity: '1 medium', estimated_cost: 0.25, category: 'Produce' },
      { name: 'Honey', quantity: '1 tsp', estimated_cost: 0.05, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-10',
    name: 'Spaghetti Bolognese',
    description: 'Slow-simmered tomato meat sauce over al dente spaghetti. A family classic.',
    category: 'dinner',
    prep_time_minutes: 15,
    cook_time_minutes: 40,
    servings: 4,
    cost_per_serving: 2.50,
    total_cost: 10.00,
    tags: ['family-friendly', 'freezer-friendly', 'meal-prep'],
    instructions: 'Brown ground beef with onion and garlic. Add crushed tomatoes, tomato paste, herbs, and simmer 30 minutes. Cook spaghetti. Serve with parmesan.',
    ingredients: [
      { name: 'Ground Beef (80/20)', quantity: '1 lb', estimated_cost: 4.50, category: 'Proteins' },
      { name: 'Spaghetti', quantity: '12 oz', estimated_cost: 1.20, category: 'Pantry' },
      { name: 'Crushed Tomatoes (canned)', quantity: '28 oz', estimated_cost: 1.50, category: 'Pantry' },
      { name: 'Tomato Paste', quantity: '2 tbsp', estimated_cost: 0.30, category: 'Pantry' },
      { name: 'Onion', quantity: '1 medium', estimated_cost: 0.30, category: 'Produce' },
      { name: 'Garlic', quantity: '3 cloves', estimated_cost: 0.20, category: 'Produce' },
      { name: 'Olive Oil', quantity: '2 tbsp', estimated_cost: 0.25, category: 'Pantry' },
      { name: 'Dried Italian Herbs', quantity: '1 tsp', estimated_cost: 0.15, category: 'Pantry' },
      { name: 'Parmesan Cheese', quantity: '¼ cup', estimated_cost: 1.00, category: 'Dairy & Eggs' },
    ],
  },
  {
    id: 'seed-11',
    name: 'Chicken Stir Fry',
    description: 'Quick high-heat stir fry with tender chicken and crisp vegetables over rice.',
    category: 'dinner',
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 4,
    cost_per_serving: 3.20,
    total_cost: 12.80,
    tags: ['high-protein', 'quick', 'healthy'],
    instructions: 'Slice chicken and marinate briefly in soy sauce. Stir fry in batches over high heat. Cook vegetables separately, combine with sauce made from soy sauce, garlic, and ginger. Serve over rice.',
    ingredients: [
      { name: 'Chicken Breast', quantity: '1.5 lb', estimated_cost: 6.00, category: 'Proteins' },
      { name: 'Broccoli', quantity: '1 head', estimated_cost: 1.50, category: 'Produce' },
      { name: 'Bell Pepper', quantity: '2', estimated_cost: 1.50, category: 'Produce' },
      { name: 'Soy Sauce', quantity: '¼ cup', estimated_cost: 0.40, category: 'Pantry' },
      { name: 'Garlic', quantity: '3 cloves', estimated_cost: 0.20, category: 'Produce' },
      { name: 'Fresh Ginger', quantity: '1 tbsp', estimated_cost: 0.25, category: 'Produce' },
      { name: 'Sesame Oil', quantity: '1 tbsp', estimated_cost: 0.30, category: 'Pantry' },
      { name: 'White Rice', quantity: '1.5 cups dry', estimated_cost: 0.60, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-12',
    name: 'Bean & Rice Bowl',
    description: 'Satisfying burrito bowl with seasoned beans, rice, corn, and avocado.',
    category: 'dinner',
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    cost_per_serving: 1.50,
    total_cost: 6.00,
    tags: ['vegan', 'meal-prep', 'budget-champion'],
    instructions: 'Cook rice. Season black beans with cumin and garlic. Assemble bowls with rice, beans, corn, salsa, and sliced avocado. Squeeze lime over top.',
    ingredients: [
      { name: 'White Rice', quantity: '1.5 cups dry', estimated_cost: 0.60, category: 'Pantry' },
      { name: 'Black Beans (canned)', quantity: '2 cans', estimated_cost: 1.60, category: 'Pantry' },
      { name: 'Corn (canned or frozen)', quantity: '1 cup', estimated_cost: 0.60, category: 'Pantry' },
      { name: 'Avocado', quantity: '2', estimated_cost: 2.00, category: 'Produce' },
      { name: 'Salsa', quantity: '½ cup', estimated_cost: 0.70, category: 'Pantry' },
      { name: 'Lime', quantity: '1', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Ground Cumin', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-13',
    name: 'Chickpea Curry',
    description: 'Creamy, fragrant chickpea curry with coconut milk. Ready in 30 minutes.',
    category: 'dinner',
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    cost_per_serving: 2.00,
    total_cost: 8.00,
    tags: ['vegan', 'gluten-free', 'meal-prep', 'freezer-friendly'],
    instructions: 'Sauté onion and garlic, add curry powder, then diced tomatoes, chickpeas, and coconut milk. Simmer 20 minutes. Serve over basmati rice with fresh cilantro.',
    ingredients: [
      { name: 'Chickpeas (canned)', quantity: '2 cans (15oz)', estimated_cost: 1.80, category: 'Pantry' },
      { name: 'Diced Tomatoes (canned)', quantity: '14 oz', estimated_cost: 0.90, category: 'Pantry' },
      { name: 'Coconut Milk (canned)', quantity: '14 oz', estimated_cost: 1.50, category: 'Pantry' },
      { name: 'Onion', quantity: '1 large', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Garlic', quantity: '3 cloves', estimated_cost: 0.20, category: 'Produce' },
      { name: 'Curry Powder', quantity: '2 tsp', estimated_cost: 0.25, category: 'Pantry' },
      { name: 'Basmati Rice', quantity: '1.5 cups dry', estimated_cost: 0.80, category: 'Pantry' },
      { name: 'Fresh Cilantro', quantity: '¼ cup', estimated_cost: 0.50, category: 'Produce' },
    ],
  },
  {
    id: 'seed-14',
    name: 'Potato Leek Soup',
    description: 'Silky blended soup with russet potatoes and sweet leeks. Elegant and cheap.',
    category: 'dinner',
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 6,
    cost_per_serving: 1.80,
    total_cost: 10.80,
    tags: ['vegetarian', 'meal-prep', 'freezer-friendly', 'comfort-food'],
    instructions: 'Sweat leeks in butter. Add potatoes and broth, simmer until tender, about 20 minutes. Blend until smooth. Stir in cream, season with salt and thyme.',
    ingredients: [
      { name: 'Russet Potatoes', quantity: '2 lbs', estimated_cost: 2.00, category: 'Produce' },
      { name: 'Leeks', quantity: '3 large', estimated_cost: 3.00, category: 'Produce' },
      { name: 'Vegetable Broth', quantity: '4 cups', estimated_cost: 1.20, category: 'Pantry' },
      { name: 'Butter', quantity: '2 tbsp', estimated_cost: 0.25, category: 'Dairy & Eggs' },
      { name: 'Heavy Cream', quantity: '½ cup', estimated_cost: 0.80, category: 'Dairy & Eggs' },
      { name: 'Garlic', quantity: '2 cloves', estimated_cost: 0.15, category: 'Produce' },
      { name: 'Fresh Thyme', quantity: '2 sprigs', estimated_cost: 0.50, category: 'Produce' },
    ],
  },
  {
    id: 'seed-15',
    name: 'Veggie Pasta Primavera',
    description: 'Seasonal vegetables tossed with pasta, garlic, olive oil, and parmesan.',
    category: 'dinner',
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    cost_per_serving: 2.20,
    total_cost: 8.80,
    tags: ['vegetarian', 'quick', 'family-friendly'],
    instructions: 'Cook pasta. Sauté zucchini and cherry tomatoes in olive oil with garlic. Toss with drained pasta, fresh basil, and parmesan. Season with salt and pepper.',
    ingredients: [
      { name: 'Penne Pasta', quantity: '12 oz', estimated_cost: 1.20, category: 'Pantry' },
      { name: 'Zucchini', quantity: '2 medium', estimated_cost: 1.50, category: 'Produce' },
      { name: 'Cherry Tomatoes', quantity: '1 cup', estimated_cost: 1.80, category: 'Produce' },
      { name: 'Garlic', quantity: '4 cloves', estimated_cost: 0.25, category: 'Produce' },
      { name: 'Olive Oil', quantity: '3 tbsp', estimated_cost: 0.40, category: 'Pantry' },
      { name: 'Parmesan Cheese', quantity: '½ cup', estimated_cost: 2.00, category: 'Dairy & Eggs' },
      { name: 'Fresh Basil', quantity: '¼ cup', estimated_cost: 0.80, category: 'Produce' },
    ],
  },
  {
    id: 'seed-16',
    name: 'Red Lentil Dahl',
    description: 'Aromatic Indian-inspired dahl with red lentils and warming spices.',
    category: 'dinner',
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 4,
    cost_per_serving: 1.60,
    total_cost: 6.40,
    tags: ['vegan', 'gluten-free', 'meal-prep', 'high-protein'],
    instructions: 'Sauté onion, garlic, and ginger. Add spices, then lentils, diced tomatoes, and coconut milk. Simmer 25 minutes until thick. Serve over rice with naan if desired.',
    ingredients: [
      { name: 'Red Lentils', quantity: '1.5 cups', estimated_cost: 1.20, category: 'Pantry' },
      { name: 'Diced Tomatoes (canned)', quantity: '14 oz', estimated_cost: 0.90, category: 'Pantry' },
      { name: 'Coconut Milk (canned)', quantity: '14 oz', estimated_cost: 1.50, category: 'Pantry' },
      { name: 'Onion', quantity: '1 large', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Garlic', quantity: '3 cloves', estimated_cost: 0.20, category: 'Produce' },
      { name: 'Ground Turmeric', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
      { name: 'Ground Cumin', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
      { name: 'Ground Coriander', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
      { name: 'Basmati Rice', quantity: '1.5 cups dry', estimated_cost: 0.80, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-17',
    name: 'Sheet Pan Chicken & Veggies',
    description: 'One-pan roasted chicken thighs with sweet potato and broccoli.',
    category: 'dinner',
    prep_time_minutes: 15,
    cook_time_minutes: 35,
    servings: 4,
    cost_per_serving: 3.50,
    total_cost: 14.00,
    tags: ['gluten-free', 'high-protein', 'meal-prep'],
    instructions: 'Toss chicken thighs and vegetables with olive oil, garlic, and paprika. Spread on a sheet pan and roast at 425°F for 35 minutes, turning halfway.',
    ingredients: [
      { name: 'Chicken Thighs (bone-in)', quantity: '4 pieces (2 lbs)', estimated_cost: 7.00, category: 'Proteins' },
      { name: 'Sweet Potatoes', quantity: '2 medium', estimated_cost: 2.00, category: 'Produce' },
      { name: 'Broccoli', quantity: '1 head', estimated_cost: 1.50, category: 'Produce' },
      { name: 'Olive Oil', quantity: '3 tbsp', estimated_cost: 0.40, category: 'Pantry' },
      { name: 'Garlic', quantity: '3 cloves', estimated_cost: 0.20, category: 'Produce' },
      { name: 'Smoked Paprika', quantity: '1 tsp', estimated_cost: 0.15, category: 'Pantry' },
      { name: 'Dried Rosemary', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-18',
    name: 'Turkey Meatball Soup',
    description: 'Comforting broth soup with turkey meatballs, pasta, and vegetables.',
    category: 'dinner',
    prep_time_minutes: 20,
    cook_time_minutes: 30,
    servings: 6,
    cost_per_serving: 2.80,
    total_cost: 16.80,
    tags: ['high-protein', 'meal-prep', 'freezer-friendly', 'comfort-food'],
    instructions: 'Mix turkey, egg, breadcrumbs, and herbs. Form into small balls and bake 15 minutes. Simmer broth with carrots and celery, add meatballs and pasta, cook until tender.',
    ingredients: [
      { name: 'Ground Turkey', quantity: '1 lb', estimated_cost: 5.00, category: 'Proteins' },
      { name: 'Chicken Broth', quantity: '8 cups', estimated_cost: 2.50, category: 'Pantry' },
      { name: 'Egg', quantity: '1', estimated_cost: 0.30, category: 'Dairy & Eggs' },
      { name: 'Breadcrumbs', quantity: '¼ cup', estimated_cost: 0.25, category: 'Pantry' },
      { name: 'Carrots', quantity: '2 medium', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Celery', quantity: '3 stalks', estimated_cost: 0.45, category: 'Produce' },
      { name: 'Small Pasta', quantity: '1 cup dry', estimated_cost: 0.50, category: 'Pantry' },
      { name: 'Dried Parsley', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
    ],
  },
  {
    id: 'seed-19',
    name: 'Hummus & Veggie Plate',
    description: 'Creamy hummus with crisp fresh vegetables for dipping. Great snack or side.',
    category: 'snack',
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 4,
    cost_per_serving: 0.80,
    total_cost: 3.20,
    tags: ['vegan', 'no-cook', 'healthy', 'quick'],
    instructions: 'Arrange hummus in a bowl. Slice carrots, celery, cucumber, and bell pepper into sticks. Serve alongside.',
    ingredients: [
      { name: 'Hummus', quantity: '1 cup', estimated_cost: 1.80, category: 'Pantry' },
      { name: 'Carrots', quantity: '2 medium', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Celery', quantity: '2 stalks', estimated_cost: 0.30, category: 'Produce' },
      { name: 'Cucumber', quantity: '1 small', estimated_cost: 0.50, category: 'Produce' },
      { name: 'Bell Pepper', quantity: '1', estimated_cost: 0.75, category: 'Produce' },
    ],
  },
  {
    id: 'seed-20',
    name: 'Baked Oatmeal',
    description: 'Make-ahead baked oatmeal with cinnamon and banana. Serves the whole week.',
    category: 'breakfast',
    prep_time_minutes: 10,
    cook_time_minutes: 35,
    servings: 6,
    cost_per_serving: 1.00,
    total_cost: 6.00,
    tags: ['vegetarian', 'meal-prep', 'kid-friendly'],
    instructions: 'Mix oats, milk, eggs, mashed bananas, honey, and cinnamon. Pour into greased baking dish. Bake at 375°F for 35 minutes until set. Slice and reheat throughout the week.',
    ingredients: [
      { name: 'Rolled Oats', quantity: '3 cups', estimated_cost: 1.20, category: 'Pantry' },
      { name: 'Milk', quantity: '2.5 cups', estimated_cost: 0.75, category: 'Dairy & Eggs' },
      { name: 'Eggs', quantity: '2 large', estimated_cost: 0.60, category: 'Dairy & Eggs' },
      { name: 'Bananas', quantity: '2 ripe', estimated_cost: 0.40, category: 'Produce' },
      { name: 'Honey', quantity: '3 tbsp', estimated_cost: 0.45, category: 'Pantry' },
      { name: 'Ground Cinnamon', quantity: '1 tsp', estimated_cost: 0.10, category: 'Pantry' },
      { name: 'Butter', quantity: '1 tbsp', estimated_cost: 0.10, category: 'Dairy & Eggs' },
    ],
  },
]

export const SHOPPING_CATEGORIES = [
  'Produce',
  'Dairy & Eggs',
  'Proteins',
  'Pantry',
  'Bread & Bakery',
  'Frozen',
  'Other',
]
